client_config_backend: file
client_config:
    client_id: 507991693733-i1koa90hb89cskjmrldoik870bdr83vm.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive